- pattern: '*'
  hosts: '/etc/ansible/hosts'
  tasks:
  - do:
    - configure template & module variables
    - setup a=2 b=3 c=4
  - do:
    - copy a file
    - copy /srv/a /srv/b
    notify: 
    - restart apache
  - do:
    - template from local file template.j2 to remote location /srv/file.out
    - template /srv/template.j2 /srv/file.out
    notify:
    - restart apache
    - quack like a duck
  - do:
    - something that will fail
    - command /bin/false
  handlers:
    - do:
      - restart apache
      - command /sbin/service httpd restart
    - do:
      - quack like a duck
      - command /bin/true
