- hosts: all
  gather_facts: no
  roles:
  - { role: test_become_r2, sudo_user: testing }
  tasks:
  - command: whoami
    become_user: testing
  - block:
    - command: whoami
    become_user: testing
